language: go

sudo: false

services:
  - docker

go:
  - tip

env:
  - DOCKERTEST_BIND_LOCALHOST=true

before_script:
 -  docker pull marketreaction/sentiment-api

script:
 -  go get -t -d -v ./...
 -  go test -v ./...

after_success:
 -  docker run -v $(pwd)/analyser:/src bdehamer/golang-builder:latest
 -  docker build analyser -t jonnyshaw89/sentiment:latest
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push jonnyshaw89/sentiment:latest