language: go

sudo: required

services:
  - docker

go:
  - tip

script:
 -  docker run -v $(pwd)/analyser:/src bdehamer/golang-builder:latest
 -  docker build analyser -t jonnyshaw89/sentiment:latest

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push jonnyshaw89/sentiment:latest